language: node_js
node_js:
  - "stable"
  - "9"
  - "8"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - npm install codecov
  - npm run lint
  - npm run testonly:cov -- --no-cache --colors && ./node_modules/.bin/codecov

notifications:
  email:
    on_success: never
